name: SonarQube Cloud Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube-scan:
    name: Static Code Analysis
    # Changed from windows-latest to ubuntu-latest
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff
        with:
          channel: 'stable'

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@e544b780808654ba8ceba5fb2fe2897103d92ff4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
